In [2]:
import torch
import torch.nn as nn

starting with an example of the neural network having\
5 input features and 10 corresponding rows(instance)

In [6]:
class Model(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear=nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

In [7]:
#create the dataset
features=torch.rand(10,5)

## create the Model 
model=Model(features.shape[1])

## call mode for forward pass
#model.forward(features) also work here pytorch uses the magic method __call__
model(features) ## standard and required way to call

tensor([[0.3965],
        [0.3608],
        [0.3875],
        [0.3608],
        [0.3219],
        [0.3568],
        [0.3352],
        [0.3671],
        [0.3826],
        [0.3528]], grad_fn=<SigmoidBackward0>)

In [9]:
# show model weights and bias
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.0927,  0.2450, -0.3244, -0.3790, -0.0874]], requires_grad=True)
Parameter containing:
tensor([-0.2836], requires_grad=True)

In [10]:
from torchinfo import summary

In [11]:
summary(model, input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

now using the hidden layers also\
5 nodes in input layers\
3 nodes in hidden layers (uses the relu activation)\
1 node in output layers (uses the sigmoid as activation)\

In [12]:
class Model2(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear=nn.Linear(num_features, 3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out

In [13]:
#create the dataset
features=torch.rand(10,5)

## create the Model 
model2=Model2(features.shape[1])

## call mode for forward pass

model2(features) ## standard and required way to call

tensor([[0.5134],
        [0.5099],
        [0.5127],
        [0.5168],
        [0.5043],
        [0.5182],
        [0.5195],
        [0.5220],
        [0.5061],
        [0.5102]], grad_fn=<SigmoidBackward0>)

In [15]:
print(model2.linear.weight)
print(model2.linear.bias)
print(model2.linear2.weight)
print(model2.linear2.bias)

Parameter containing:
tensor([[-0.0888, -0.2005,  0.3963,  0.1424, -0.1112],
        [-0.2878,  0.3575, -0.0536, -0.0275,  0.3203],
        [-0.4068, -0.0282,  0.2727, -0.2443,  0.1265]], device='cuda:0',
       requires_grad=True)
Parameter containing:
tensor([ 0.4142,  0.2690, -0.2129], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([[0.1676, 0.0361, 0.0119]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0461], device='cuda:0', requires_grad=True)

In [14]:
summary(model2,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

## now i am simplifying this model creation by using the containers

In [19]:
# using Sequential container
class Model3(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        

    def forward(self, features):
        out=self.network(features)

        return out

In [20]:
model3=Model3(features.shape[1])
model3(features)

tensor([[0.3119],
        [0.3251],
        [0.3136],
        [0.3228],
        [0.3240],
        [0.3264],
        [0.3112],
        [0.3263],
        [0.3307],
        [0.3158]], grad_fn=<SigmoidBackward0>)

In [21]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [22]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [23]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [27]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [28]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [29]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [30]:
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [38]:
type(X_train[0][9])

numpy.float64

In [42]:
X_train_tensor=torch.from_numpy(X_train).to(torch.float32)
X_test_tensor=torch.from_numpy(X_test).to(torch.float32)
y_train_tensor=torch.from_numpy(y_train).to(torch.float32)
y_test_tensor=torch.from_numpy(y_test).to(torch.float32)

In [32]:
class mySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    def loss_function(self, y, y_pred):
        # Clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred, epsilon, 1-epsilon)
        #calculate the loss
        loss = -(y*torch.log(y_pred) + (1-y)*(1-y_pred)).mean()
        return loss

important paramerters

In [33]:
learning_rate = 0.1
epochs = 25

In [43]:
# create the model 
model=mySimpleNN(X_train_tensor.shape[1])

# define loop 
for epoch in range(epochs):

    # forward pass
    y_pred= model(X_train_tensor)
    #print(y_pred)
    
    # loss calculate
    loss = model.loss_function(y_train_tensor, y_pred)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate*model.linear.bias.grad

    ## zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # print the loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: -0.060158971697092056
Epoch: 2, Loss: -0.06092168018221855
Epoch: 3, Loss: -0.06160157546401024
Epoch: 4, Loss: -0.062211811542510986
Epoch: 5, Loss: -0.06276310235261917
Epoch: 6, Loss: -0.06326424330472946
Epoch: 7, Loss: -0.06372241675853729
Epoch: 8, Loss: -0.06414352357387543
Epoch: 9, Loss: -0.06453242152929306
Epoch: 10, Loss: -0.06489315629005432
Epoch: 11, Loss: -0.06522905826568604
Epoch: 12, Loss: -0.06554294377565384
Epoch: 13, Loss: -0.06583712995052338
Epoch: 14, Loss: -0.06611359864473343
Epoch: 15, Loss: -0.0663740336894989
Epoch: 16, Loss: -0.0666198804974556
Epoch: 17, Loss: -0.06685233861207962
Epoch: 18, Loss: -0.06707249581813812
Epoch: 19, Loss: -0.06728128343820572
Epoch: 20, Loss: -0.06747952103614807
Epoch: 21, Loss: -0.06766790896654129
Epoch: 22, Loss: -0.0678471177816391
Epoch: 23, Loss: -0.06801772117614746
Epoch: 24, Loss: -0.06818022578954697
Epoch: 25, Loss: -0.06833512336015701

In [44]:
model.linear.weight

Parameter containing:
tensor([[ 0.0043, -0.0733,  0.1107, -0.1005, -0.0455, -0.0598,  0.0556,  0.1874,
         -0.0424, -0.0159,  0.0090, -0.0472, -0.0493, -0.0715, -0.0707, -0.0207,
         -0.0296, -0.1066, -0.0878,  0.1359,  0.0386, -0.0683, -0.1283, -0.0044,
         -0.0106, -0.1270,  0.1141,  0.1015,  0.1096,  0.0623]],
       requires_grad=True)

In [45]:
model.linear.bias

Parameter containing:
tensor([0.1988], requires_grad=True)

Now we are making our model fully automatic in calculating the loss function and parameter optimization step... by using the inbuilt function...

In [52]:
## defining the loss function
loss_function = nn.BCELoss()


class mySimpleNN2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out
    
# create the model 
model=mySimpleNN2(X_train_tensor.shape[1])

# defining the optimizer
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

    # forward pass
    y_pred= model(X_train_tensor)
    #print(y_pred)
    
    # loss calculate
    loss = loss_function( y_pred, y_train_tensor.view(-1,1))

    ## zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print the loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6566649675369263
Epoch: 2, Loss: 0.5113856792449951
Epoch: 3, Loss: 0.43302062153816223
Epoch: 4, Loss: 0.38334518671035767
Epoch: 5, Loss: 0.34846797585487366
Epoch: 6, Loss: 0.3223014771938324
Epoch: 7, Loss: 0.3017398416996002
Epoch: 8, Loss: 0.28502357006073
Epoch: 9, Loss: 0.2710762023925781
Epoch: 10, Loss: 0.2591995298862457
Epoch: 11, Loss: 0.2489192932844162
Epoch: 12, Loss: 0.23990079760551453
Epoch: 13, Loss: 0.2319006323814392
Epoch: 14, Loss: 0.2247367650270462
Epoch: 15, Loss: 0.21827024221420288
Epoch: 16, Loss: 0.21239283680915833
Epoch: 17, Loss: 0.20701885223388672
Epoch: 18, Loss: 0.20207937061786652
Epoch: 19, Loss: 0.19751831889152527
Epoch: 20, Loss: 0.19328941404819489
Epoch: 21, Loss: 0.1893542855978012
Epoch: 22, Loss: 0.18568050861358643
Epoch: 23, Loss: 0.18224076926708221
Epoch: 24, Loss: 0.17901161313056946
Epoch: 25, Loss: 0.17597292363643646