In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [8]:
## Scaling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_train

array([[-0.5612003 ,  0.17831004, -0.53217506, ..., -0.51713   ,
        -0.31603437,  0.27295224],
       [-1.39458751, -1.23663274, -1.33742377, ..., -0.6440897 ,
         1.27716014,  0.35406721],
       [ 0.11120784, -1.29193994,  0.07950029, ..., -0.34836275,
        -0.45207876, -0.74297029],
       ...,
       [-0.86606331, -1.42559903, -0.88712836, ..., -0.91399434,
        -0.07017102, -0.89952787],
       [-0.32471778, -1.25045954, -0.39844846, ..., -1.21740651,
        -1.30276596, -1.00843749],
       [ 1.43038144, -0.16044662,  1.36765059, ...,  1.45366573,
         1.04113133, -0.03619225]], shape=(455, 30))

In [10]:
y_train

506    B
520    B
513    B
494    B
346    B
      ..
446    M
169    B
153    B
309    B
56     M
Name: diagnosis, Length: 455, dtype: str

In [11]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

### Numpy array to PyTorch Module

In [12]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
X_train_tensor

tensor([[-0.5612,  0.1783, -0.5322,  ..., -0.5171, -0.3160,  0.2730],
        [-1.3946, -1.2366, -1.3374,  ..., -0.6441,  1.2772,  0.3541],
        [ 0.1112, -1.2919,  0.0795,  ..., -0.3484, -0.4521, -0.7430],
        ...,
        [-0.8661, -1.4256, -0.8871,  ..., -0.9140, -0.0702, -0.8995],
        [-0.3247, -1.2505, -0.3984,  ..., -1.2174, -1.3028, -1.0084],
        [ 1.4304, -0.1604,  1.3677,  ...,  1.4537,  1.0411, -0.0362]],
       dtype=torch.float64)

### Define the Model

In [35]:
class mySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1 , dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1 , dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) - self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y, y_pred):
        # Clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred, epsilon, 1-epsilon)
        #calculate the loss
        loss = -(y*torch.log(y_pred) + (1-y)*(1-y_pred)).mean()
        return loss

In [36]:
learning_rate=0.1
epochs = 25

### Training PipeLine

In [37]:
## create the model 
model = mySimpleNN(X_train_tensor)

In [38]:
model.weights

tensor([[0.3440],
        [0.7948],
        [0.2499],
        [0.9947],
        [0.3296],
        [0.3704],
        [0.9131],
        [0.2059],
        [0.7439],
        [0.2585],
        [0.9850],
        [0.4441],
        [0.7963],
        [0.8829],
        [0.7422],
        [0.7445],
        [0.0588],
        [0.4334],
        [0.6669],
        [0.4717],
        [0.4880],
        [0.5938],
        [0.8872],
        [0.8395],
        [0.5111],
        [0.5987],
        [0.1285],
        [0.2334],
        [0.7355],
        [0.5210]], dtype=torch.float64, requires_grad=True)

In [39]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [40]:
## training the model 

# define loop 
for epoch in range(epochs):

    # forward pass
    y_pred= model.forward(X_train_tensor)
    #print(y_pred)
    
    # loss calculate
    loss = model.loss_function(y_train_tensor, y_pred)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    ## zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print the loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.2628232903061962
Epoch: 2, Loss: 1.2283071176628504
Epoch: 3, Loss: 1.1939599333094246
Epoch: 4, Loss: 1.159788872221362
Epoch: 5, Loss: 1.1258020083424924
Epoch: 6, Loss: 1.0920085546012208
Epoch: 7, Loss: 1.0584190099654516
Epoch: 8, Loss: 1.0250452464093405
Epoch: 9, Loss: 0.9919005344761905
Epoch: 10, Loss: 0.9589995090644634
Epoch: 11, Loss: 0.9263580796870522
Epoch: 12, Loss: 0.8939932896940996
Epoch: 13, Loss: 0.8619231308278124
Epoch: 14, Loss: 0.8301663220343043
Epoch: 15, Loss: 0.7987420674326138
Epoch: 16, Loss: 0.7676698129832766
Epoch: 17, Loss: 0.736969026632159
Epoch: 18, Loss: 0.7066590302028907
Epoch: 19, Loss: 0.6767589095369639
Epoch: 20, Loss: 0.6472875230832985
Epoch: 21, Loss: 0.6182636177570916
Epoch: 22, Loss: 0.5897060443663154
Epoch: 23, Loss: 0.561634048870003
Epoch: 24, Loss: 0.5340675996144415
Epoch: 25, Loss: 0.5070277008995981

In [41]:
model.weights

tensor([[ 0.0919],
        [ 0.6037],
        [-0.0129],
        [ 0.7470],
        [ 0.1173],
        [ 0.0604],
        [ 0.5924],
        [-0.1189],
        [ 0.5138],
        [ 0.1399],
        [ 0.7368],
        [ 0.3333],
        [ 0.5481],
        [ 0.6691],
        [ 0.6550],
        [ 0.4974],
        [-0.1535],
        [ 0.1714],
        [ 0.5608],
        [ 0.2817],
        [ 0.2151],
        [ 0.3981],
        [ 0.6051],
        [ 0.5787],
        [ 0.3128],
        [ 0.3190],
        [-0.1747],
        [-0.0900],
        [ 0.5381],
        [ 0.3127]], dtype=torch.float64, requires_grad=True)

In [65]:
## model evaluation

with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    ## convert it into the binary
    y_pred = (y_pred > 0.95).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy Score: {accuracy.item()}' )

Accuracy Score: 0.5549399852752686

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.]])